/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.FrontDesk.DashboardPanels;

import java.awt.CardLayout;

/**
 *
 * @author ADMIN
 */
public class BasePanel extends javax.swing.JPanel {

    /**
     * Creates new form BasePanel
     */
    
    CardLayout cardLayout = new CardLayout();
    public BasePanel() {
        initComponents();
        setLayout(cardLayout);

       // floor1 = new GUI.FrontDesk.DashboardPanels.Floor1();
        floor2 = new GUI.FrontDesk.DashboardPanels.Floor2();

      //  add(floor1, "floor1");
        add(floor2, "floor2");

        cardLayout.show(this, "floor1");
    }
    public void showFloor(String floorName) {
        cardLayout.show(this, floorName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floor2 = new GUI.FrontDesk.DashboardPanels.Floor2();
        floor11 = new GUI.FrontDesk.DashboardPanels.Floor1();

        setPreferredSize(new java.awt.Dimension(869, 449));
        setLayout(new java.awt.CardLayout());
        add(floor2, "card2");
        add(floor11, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.FrontDesk.DashboardPanels.Floor1 floor11;
    private GUI.FrontDesk.DashboardPanels.Floor2 floor2;
    // End of variables declaration//GEN-END:variables
}
