/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.FrontDesk.DashboardPanels;

/**
 *
 * @author ADMIN
 */
public class Floor1 extends javax.swing.JPanel {

    /**
     * Creates new form BasePanel
     */
    
    public Floor1() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        roomPanel5 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel1 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel2 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel3 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel4 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel10 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel15 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel14 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel13 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel9 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel8 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel6 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel7 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel12 = new GUI.FrontDesk.DashboardPanels.RoomPanel();
        roomPanel11 = new GUI.FrontDesk.DashboardPanels.RoomPanel();

        setBackground(new java.awt.Color(19, 19, 19));
        setMaximumSize(new java.awt.Dimension(869, 439));
        setMinimumSize(new java.awt.Dimension(869, 439));
        setPreferredSize(new java.awt.Dimension(869, 439));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 11));
        jPanel3.add(roomPanel5);
        jPanel3.add(roomPanel1);
        jPanel3.add(roomPanel2);
        jPanel3.add(roomPanel3);
        jPanel3.add(roomPanel4);
        jPanel3.add(roomPanel10);
        jPanel3.add(roomPanel15);
        jPanel3.add(roomPanel14);
        jPanel3.add(roomPanel13);
        jPanel3.add(roomPanel9);
        jPanel3.add(roomPanel8);
        jPanel3.add(roomPanel6);
        jPanel3.add(roomPanel7);
        jPanel3.add(roomPanel12);
        jPanel3.add(roomPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel1;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel10;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel11;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel12;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel13;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel14;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel15;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel2;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel3;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel4;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel5;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel6;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel7;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel8;
    private GUI.FrontDesk.DashboardPanels.RoomPanel roomPanel9;
    // End of variables declaration//GEN-END:variables
}
