/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.FrontDesk.DashboardPanels;

import Database.DBConnection;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class RoomPanel extends javax.swing.JPanel {
    private String roomNo, status, checkOut, price, type;
    /**
     * Creates new form RoomPanel
     */
    Connection conn;
    public RoomPanel() {
        conn = DBConnection.connectDB();
        initComponents();
        setOpaque(false);
    }

    public void setRoomNo(String roomNo){
        this.roomNo = roomNo;
        jLabel1.setText(roomNo);
    }
    
    public void setStatus(String status) {
    this.status = status;

    if ("Available".equalsIgnoreCase(status)) {
        jButton2.setEnabled(false);
        curvedPanel1.setBackground(new Color(76,175,80)); 
    } else {
        jButton2.setEnabled(true);
        curvedPanel1.setBackground(new Color(255, 191, 0));
    }

    jLabel3.setText("Status: " + status);
}

    
    public void setCheckOut(String checkOut){
        this.checkOut = checkOut;
        if(checkOut == null || checkOut.trim().isEmpty()){
        jLabel4.setText("Check-Out: ");
    } else {
        jLabel4.setText("Check-Out: " + checkOut);
    }
    }
    
    public void setRoomDetails(String price, String type){
        this.price = price;
        this.type = type;
        
        jLabel2.setText(price + " / " + type);
    }
    
    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curvedPanel1 = new CustomElements.CurvedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(42, 42, 42));
        setMaximumSize(new java.awt.Dimension(160, 132));
        setMinimumSize(new java.awt.Dimension(160, 132));
        setPreferredSize(new java.awt.Dimension(160, 132));

        curvedPanel1.setBackground(new java.awt.Color(76, 175, 80));
        curvedPanel1.setRoundBottomLeft(90);
        curvedPanel1.setRoundBottomRight(90);
        curvedPanel1.setRoundTopLeft(90);
        curvedPanel1.setRoundTopRight(90);

        jLabel1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(212, 171, 97));
        jLabel1.setText("000");

        jLabel2.setForeground(new java.awt.Color(212, 171, 97));
        jLabel2.setText("Price/Type");

        jLabel3.setForeground(new java.awt.Color(212, 171, 97));
        jLabel3.setText("Status:");

        jButton2.setBackground(new java.awt.Color(212, 171, 97));
        jButton2.setForeground(new java.awt.Color(19, 19, 19));
        jButton2.setText("View Details");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(212, 171, 97));
        jLabel4.setText("Check-Out:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(curvedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(curvedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addGap(173, 173, 173))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        try (PreparedStatement pst = conn.prepareStatement("SELECT GuestID FROM RoomList WHERE Room_Number = " + roomNo)) {
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int guestId = rs.getInt("GuestID");

                try (PreparedStatement guestPst = conn.prepareStatement(
                    "SELECT FullName, Email, BirthDate, Gender, Nationality, IDType, IDNumber, " +
                    "CheckIn, CheckOut, NumberOfGuest, ExtraBed, Laundry " +
                    "FROM Guest_Information WHERE BookingID = ?")) {

                    guestPst.setInt(1, guestId);
                    ResultSet guestRs = guestPst.executeQuery();

                    if (guestRs.next()) {
                        String fullName = guestRs.getString("FullName");
                        String email = guestRs.getString("Email");
                        String birthDate = guestRs.getString("BirthDate");
                        String gender = guestRs.getString("Gender");
                        String nationality = guestRs.getString("Nationality");
                        String idType = guestRs.getString("IDType");
                        String idNumber = guestRs.getString("IDNumber");
                        String checkIn = guestRs.getString("CheckIn");
                        String checkOut = guestRs.getString("CheckOut");
                        int numberOfGuests = guestRs.getInt("NumberOfGuest");
                        int extraBed = guestRs.getInt("ExtraBed");
                        boolean laundry = guestRs.getBoolean("Laundry");

                        String guestInfo = "=== GUEST INFORMATION ===\n\n" +
                                         "Guest Name: " + fullName + "\n" +
                                         "Email: " + email + "\n" +
                                         "Birth Date: " + birthDate + "\n" +
                                         "Gender: " + gender + "\n" +
                                         "Nationality: " + nationality + "\n" +
                                         "ID Type: " + idType + "\n" +
                                         "ID Number: " + idNumber + "\n\n" +
                                         "=== ROOM DETAILS ===\n\n" +
                                         "Check-in Date: " + checkIn + "\n" +
                                         "Check-out Date: " + checkOut + "\n" +
                                         "Number of Guests: " + numberOfGuests + "\n" +
                                         "Extra Bed: " + extraBed + "\n" +
                                         "Laundry Service: " + (laundry ? "Yes" : "No");

                        JOptionPane.showMessageDialog(null, guestInfo, "Guest Details", JOptionPane.INFORMATION_MESSAGE);
                    }}} 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomElements.CurvedPanel curvedPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
