/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.FrontDesk.Management.GuestManagement;

import Database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class CheckOut extends javax.swing.JPanel {

    /**
     * Creates new form CheckOut
     */
    Connection conn;
    public CheckOut() {
        conn = DBConnection.connectDB();
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initTable() {
        DefaultTableModel dt = (DefaultTableModel) guestList.getModel();
        dt.setRowCount(0);

        String sql = """
            SELECT BookingID,
                   gi.FullName,
                   rl.Room_Number,
                   rl.CheckIn,
                   rl.CheckOut,
                   rr.Price_Rate
            FROM Guest_Information gi
            JOIN RoomList rl ON gi.RoomNumber = rl.Room_Number
            JOIN Room_Rate rr ON rl.Room_Type = rr.Room_Type
            """;

        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String bookingID = String.format("R%05d", rs.getInt("BookingID"));
                String fullName = rs.getString("FullName");
                String roomNumber = rs.getString("Room_Number");
                String checkIn = rs.getString("CheckIn");
                String checkOut = rs.getString("CheckOut");

                dt.addRow(new Object[]{bookingID, fullName, roomNumber, checkIn, checkOut});
            }

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for (int i = 0; i < guestList.getColumnCount(); i++) {
                guestList.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void receiptTable(int bookingId){
    String sql = """
        SELECT gi.BookingID,
               gi.FullName,
               gi.NumberOfGuest,
               gi.PaymentStatus,
               gi.ExtraLinen,
               gi.ExtraBed,
               gi.Laundry,
               gi.MiniBar,
               gi.EarlyIn,
               gi.Parking,
               rl.Room_Number,
               rl.Room_Type,
               rl.CheckIn,
               rl.CheckOut
        FROM Guest_Information gi
        JOIN RoomList rl ON gi.RoomNumber = rl.Room_Number
        WHERE gi.BookingID = ?
    """;
    
    try(PreparedStatement pst = conn.prepareStatement(sql)){
        pst.setInt(1, bookingId);
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()){
            // Clear existing table data
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            
            // Get room type and base price
            String roomType = rs.getString("Room_Type");
            double basePrice = getRoomPrice(roomType);
            
            // Add base room charge
            model.addRow(new Object[]{
                "Room (" + roomType + ")",
                rs.getInt("NumberOfGuest") + " guest(s)",
                String.format("₱%.2f", basePrice),
                String.format("₱%.2f", basePrice)
            });
            
            double totalAmount = basePrice;
            
            // Add extra services if selected
            if (rs.getInt("ExtraLinen") >= 1) {
                double extraLinenPrice = 500.0;
                model.addRow(new Object[]{"Extra Linen", "", String.format("₱%.2f", extraLinenPrice), String.format("₱%.2f", extraLinenPrice)});
                totalAmount += extraLinenPrice;
            }

            if (rs.getBoolean("ExtraBed")) {
                double extraBedPrice = 1000.0;
                model.addRow(new Object[]{"Extra Bed", "1", String.format("₱%.2f", extraBedPrice), String.format("₱%.2f", extraBedPrice)});
                totalAmount += extraBedPrice;
            }

            if (rs.getBoolean("Laundry")) {
                double laundryPrice = 300.0;
                model.addRow(new Object[]{"Laundry Service", "1", String.format("₱%.2f", laundryPrice), String.format("₱%.2f", laundryPrice)});
                totalAmount += laundryPrice;
            }

            if (rs.getBoolean("MiniBar")) {
                double miniBarPrice = 800.0;
                model.addRow(new Object[]{"Mini Bar", "1", String.format("₱%.2f", miniBarPrice), String.format("₱%.2f", miniBarPrice)});
                totalAmount += miniBarPrice;
            }

            if (rs.getBoolean("EarlyIn")) {
                double earlyInPrice = 200.0;
                model.addRow(new Object[]{"Early Check-in", "1", String.format("₱%.2f", earlyInPrice), String.format("₱%.2f", earlyInPrice)});
                totalAmount += earlyInPrice;
            }

            if (rs.getBoolean("Parking")) {
                double parkingPrice = 150.0;
                model.addRow(new Object[]{"Parking", "1", String.format("₱%.2f", parkingPrice), String.format("₱%.2f", parkingPrice)});
                totalAmount += parkingPrice;
            }

            
            // Update total label (assuming you have a label for total)
            // jLabelTotal.setText(String.format("Total: ₱%.2f", totalAmount));
            
            // Update guest information fields
            // jLabelBookingID.setText(rs.getString("BookingID"));
            // jLabelGuestName.setText(rs.getString("FullName"));
            // jLabelRoomNo.setText(rs.getString("Room_Number"));
            // jLabelCheckIn.setText(rs.getString("CheckIn"));
            // jLabelCheckOut.setText(rs.getString("CheckOut"));
            // jLabelPaymentStatus.setText(rs.getString("PaymentStatus"));
        }
        
    } catch(SQLException e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading receipt data: " + e.getMessage());
    }
}

    private double getRoomPrice(String roomType){
        switch(roomType.toLowerCase()){
            case "deluxe": return 9219.0;
            case "double": return 6459.0;
            case "executive": return 11990.0;
            case "presidential": return 44999.0;
            case "single": return 4259.0;
            case "suite": return 15999.0;
            case "twin": return 6999.0;
            default: return 0.0;
        }
    }
    
    private void generateReceiptPDF() {
    
    int selectedRow = guestList.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a guest first!");
        return;
    }

    try {
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd_HHmmss");
        String timestamp = dateFormat.format(new Date());
        String bookingNumber = bookingLbl.getText().replace("Booking ID: ", "").replace(" ", "");
        String baseFileName = "Receipt_" + bookingNumber + "_" + timestamp + ".pdf";
        
        // Choose save location
        String selectedPath = chooseSaveLocation(baseFileName);
        if (selectedPath == null) {
            return; // User cancelled
        }
        
        // Create document with custom page size for thermal printer (58mm width)
        Rectangle pageSize = new Rectangle(164f, 842f); // Width: 58mm, Height: variable
        Document document = new Document(pageSize, 5, 5, 10, 10); // Small margins
        
        PdfWriter.getInstance(document, new FileOutputStream(selectedPath));
        document.open();

        // Define fonts
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.BLACK);
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, BaseColor.BLACK);
        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 7, BaseColor.BLACK);
        Font smallFont = FontFactory.getFont(FontFactory.HELVETICA, 6, BaseColor.BLACK);

        // Hotel Header
        Paragraph hotelName = new Paragraph("HOTEL LA SOUVERAIN", titleFont);
        hotelName.setAlignment(Element.ALIGN_CENTER);
        document.add(hotelName);
        
        Paragraph address = new Paragraph("Clark Freeport Zone\nMabalacat, Pampanga 2023\nTel: 0928-870-2278", smallFont);
        address.setAlignment(Element.ALIGN_CENTER);
        address.setSpacingAfter(10);
        document.add(address);

        // Add line separator
        document.add(new Paragraph("===========================================", smallFont));

        // Receipt Title
        Paragraph receiptTitle = new Paragraph("CHECKOUT RECEIPT", headerFont);
        receiptTitle.setAlignment(Element.ALIGN_CENTER);
        receiptTitle.setSpacingAfter(5);
        document.add(receiptTitle);

        // Date and Time
        SimpleDateFormat receiptDateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Paragraph dateTime = new Paragraph("Date: " + receiptDateFormat.format(new Date()), normalFont);
        dateTime.setAlignment(Element.ALIGN_CENTER);
        dateTime.setSpacingAfter(10);
        document.add(dateTime);

        document.add(new Paragraph("===========================================", smallFont));

        // Guest Information
        document.add(new Paragraph("GUEST INFORMATION", headerFont));
        document.add(new Paragraph("-------------------------------------------------", smallFont));
        
        document.add(new Paragraph(bookingLbl.getText(), normalFont));
        document.add(new Paragraph(guestNameLbl.getText(), normalFont));
        document.add(new Paragraph(roomLbl.getText(), normalFont));
        document.add(new Paragraph(checkInLbl.getText(), normalFont));
        document.add(new Paragraph(checkOutLbl.getText(), normalFont));
        
        document.add(new Paragraph("===========================================", smallFont));

        // Billing Details
        document.add(new Paragraph("BILLING DETAILS", headerFont));
        document.add(new Paragraph("-------------------------------------------------", smallFont));

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        double grandTotal = 0.0;

        // Add each billing item
        for (int i = 0; i < model.getRowCount(); i++) {
            String description = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString() : "";
            String quantity = model.getValueAt(i, 1) != null ? model.getValueAt(i, 1).toString() : "";
            String unitPrice = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString() : "";
            String total = model.getValueAt(i, 3) != null ? model.getValueAt(i, 3).toString() : "";

            if (!description.isEmpty()) {
                // Item description
                document.add(new Paragraph(description, normalFont));
                
                // Quantity and unit price on same line
                String qtyPrice = quantity + " x " + unitPrice;
                Paragraph qtyPricePara = new Paragraph(qtyPrice, smallFont);
                document.add(qtyPricePara);
                
                // Total amount aligned right
                Paragraph totalPara = new Paragraph(total, normalFont);
                totalPara.setAlignment(Element.ALIGN_RIGHT);
                totalPara.setSpacingAfter(3);
                document.add(totalPara);

                // Extract numeric value from total for grand total calculation
                try {
                    String numericTotal = total.replace("₱", "").replace(",", "");
                    grandTotal += Double.parseDouble(numericTotal);
                } catch (NumberFormatException e) {
                    // Ignore if can't parse
                }
            }
        }

        document.add(new Paragraph("-------------------------------------------------", smallFont));

        // Grand Total
        Paragraph grandTotalPara = new Paragraph("TOTAL: ₱" + String.format("%.2f", grandTotal), headerFont);
        grandTotalPara.setAlignment(Element.ALIGN_RIGHT);
        grandTotalPara.setSpacingAfter(10);
        document.add(grandTotalPara);

        document.add(new Paragraph("===========================================", smallFont));

        // Footer
        document.add(new Paragraph("Thank you for staying with us!", normalFont));
        document.add(new Paragraph("Have a pleasant day!", normalFont));
        
        Paragraph footer = new Paragraph("\nPowered by Hotel Management System", smallFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(15);
        document.add(footer);

        document.close();

            try {
                java.awt.Desktop.getDesktop().open(new java.io.File(selectedPath));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Could not open the file: " + ex.getMessage());
            }

    } catch (DocumentException | IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error generating receipt: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private String chooseSaveLocation(String defaultFileName) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Receipt As...");

        // Set default save location to Documents/Hotel_Receipts folder
        String documentsPath = System.getProperty("user.home") + File.separator + "Documents" + File.separator + "Hotel_Receipts";
        File documentsDir = new File(documentsPath);
        if (!documentsDir.exists()) {
            documentsDir.mkdirs();
        }
        fileChooser.setCurrentDirectory(documentsDir);

        // Set the default filename
        fileChooser.setSelectedFile(new File(defaultFileName));

        // Set file filter for PDF files only
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("PDF Files", "pdf"));

        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String savePath = fileChooser.getSelectedFile().getAbsolutePath();
            // Ensure the file has .pdf extension
            if (!savePath.toLowerCase().endsWith(".pdf")) {
                savePath += ".pdf";
            }
            return savePath;
        }

        return null; // User cancelled
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guestList = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        bookingLbl = new javax.swing.JLabel();
        roomLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        guestNameLbl = new javax.swing.JLabel();
        checkInLbl = new javax.swing.JLabel();
        checkOutLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        receiptButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 639));
        setMinimumSize(new java.awt.Dimension(1280, 639));

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(212, 171, 97));
        jLabel10.setText("Guest List:");

        guestList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Guest Name", "Room No.", "Check-In Date", "Check-Out Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        guestList.getTableHeader().setReorderingAllowed(false);
        guestList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(guestList);
        if (guestList.getColumnModel().getColumnCount() > 0) {
            guestList.getColumnModel().getColumn(0).setResizable(false);
            guestList.getColumnModel().getColumn(1).setResizable(false);
            guestList.getColumnModel().getColumn(2).setResizable(false);
            guestList.getColumnModel().getColumn(3).setResizable(false);
            guestList.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(212, 171, 97));
        jLabel11.setText("Guest Information:");

        bookingLbl.setForeground(new java.awt.Color(212, 171, 97));
        bookingLbl.setText("Booking ID:");

        roomLbl.setForeground(new java.awt.Color(212, 171, 97));
        roomLbl.setText("Room No:");

        statusLbl.setForeground(new java.awt.Color(212, 171, 97));
        statusLbl.setText("Payment Status:");

        guestNameLbl.setForeground(new java.awt.Color(212, 171, 97));
        guestNameLbl.setText("Guest Name:");

        checkInLbl.setForeground(new java.awt.Color(212, 171, 97));
        checkInLbl.setText("Check-In Date:");

        checkOutLbl.setForeground(new java.awt.Color(212, 171, 97));
        checkOutLbl.setText("Check-Out Date:");

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(212, 171, 97));
        jLabel12.setText("Billing:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Description", "Quantity", "Unit Price", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(212, 171, 97));
        jLabel7.setText("Total:");

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(212, 171, 97));
        jLabel8.setText("Manual Charge:");

        jLabel9.setForeground(new java.awt.Color(212, 171, 97));
        jLabel9.setText("Description:");

        jLabel13.setForeground(new java.awt.Color(212, 171, 97));
        jLabel13.setText("Quantity:");

        jLabel14.setForeground(new java.awt.Color(212, 171, 97));
        jLabel14.setText("Unit Price:");

        jButton1.setText("Add");

        jButton2.setText("Clear");

        jButton3.setText("Confirm Checkout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        receiptButton.setText("Print Receipt");
        receiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Update Charge");

        jButton6.setText("Remove Charge");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkInLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guestNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(receiptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(447, 447, 447)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guestNameLbl)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bookingLbl)
                                    .addComponent(statusLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roomLbl)
                                    .addComponent(checkInLbl)
                                    .addComponent(checkOutLbl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(receiptButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guestListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestListMouseClicked
                                      
    int row = guestList.getSelectedRow();

    if (row == -1) return;

    String selection = guestList.getModel().getValueAt(row, 0).toString();
    int bookingId = Integer.parseInt(selection.substring(1)); 

    String sql = """
        SELECT gi.BookingID,
               gi.FullName,
               rl.Room_Number,
               rl.CheckIn,
               rl.CheckOut,
               gi.PaymentStatus
        FROM Guest_Information gi
        JOIN RoomList rl ON gi.RoomNumber = rl.Room_Number
        WHERE gi.BookingID = ?
    """;

    try (PreparedStatement pst = conn.prepareStatement(sql)) {
        pst.setInt(1, bookingId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            bookingLbl.setText("Booking ID: " + String.format("R%05d", rs.getInt("BookingID")));
            guestNameLbl.setText("Guest Name: " + rs.getString("FullName"));
            statusLbl.setText("Payment Status: " + rs.getString("PaymentStatus"));
            roomLbl.setText("Room No: " + rs.getString("Room_Number"));
            checkInLbl.setText("Check-In Date: " + rs.getString("CheckIn"));
            checkOutLbl.setText("Check-Out Date: " + rs.getString("CheckOut"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        receiptTable(bookingId);
    }//GEN-LAST:event_guestListMouseClicked

    private void receiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptButtonActionPerformed
        generateReceiptPDF();
    }//GEN-LAST:event_receiptButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingLbl;
    private javax.swing.JLabel checkInLbl;
    private javax.swing.JLabel checkOutLbl;
    private javax.swing.JTable guestList;
    private javax.swing.JLabel guestNameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton receiptButton;
    private javax.swing.JLabel roomLbl;
    private javax.swing.JLabel statusLbl;
    // End of variables declaration//GEN-END:variables
}
