/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.FrontDesk.Management;

/**
 *
 * @author ADMIN
 */
public class Reservations extends javax.swing.JPanel {

    /**
     * Creates new form Reservations
     */
    public Reservations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guestName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guestName1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guestName2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        guestName3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guestName4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        guestName5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DoubleCheck = new javax.swing.JCheckBox();
        singleCheck = new javax.swing.JCheckBox();
        TwinCheck = new javax.swing.JCheckBox();
        ExecuteiveCheck = new javax.swing.JCheckBox();
        DeluxeCheck = new javax.swing.JCheckBox();
        SuiteCheck = new javax.swing.JCheckBox();
        PresedentialCheck = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        singleCheck1 = new javax.swing.JCheckBox();
        DoubleCheck1 = new javax.swing.JCheckBox();
        TwinCheck1 = new javax.swing.JCheckBox();
        singleCheck2 = new javax.swing.JCheckBox();
        singleCheck3 = new javax.swing.JCheckBox();
        singleCheck4 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setMaximumSize(new java.awt.Dimension(1280, 639));
        setMinimumSize(new java.awt.Dimension(1280, 639));

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Guest Name", "Check-In Date", "Payment Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 339, -1, 254));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(212, 171, 97));
        jLabel10.setText("Reserved Guests:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 303, 168, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 305, 200, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(212, 171, 97));
        jLabel11.setText("New Reservation:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, 168, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(212, 171, 97));
        jLabel12.setText("Reservation Details:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 303, -1, -1));

        jButton1.setText("Edit");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 605, 121, -1));

        jButton2.setText("Remove Reservation");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 605, 175, -1));

        jButton3.setText("Check-In");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 605, 126, -1));

        jLabel1.setForeground(new java.awt.Color(212, 171, 97));
        jLabel1.setText("Reservation ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 339, 171, -1));

        jLabel2.setForeground(new java.awt.Color(212, 171, 97));
        jLabel2.setText("Guest Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 339, 200, -1));
        jPanel1.add(guestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 75, 175, -1));

        jLabel3.setForeground(new java.awt.Color(212, 171, 97));
        jLabel3.setText("Full Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 54, 64, -1));
        jPanel1.add(guestName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 75, 175, -1));

        jLabel4.setForeground(new java.awt.Color(212, 171, 97));
        jLabel4.setText("Contact Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 54, -1, -1));
        jPanel1.add(guestName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 75, 175, -1));

        jLabel5.setForeground(new java.awt.Color(212, 171, 97));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 54, -1, -1));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 99, -1));

        jLabel17.setForeground(new java.awt.Color(212, 171, 97));
        jLabel17.setText("Number of Guests:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel13.setForeground(new java.awt.Color(212, 171, 97));
        jLabel13.setText("Room Types:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        jPanel1.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 101, -1));

        jLabel18.setForeground(new java.awt.Color(212, 171, 97));
        jLabel18.setText("Number of Rooms:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        jPanel1.add(guestName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 75, 175, -1));

        jLabel6.setForeground(new java.awt.Color(212, 171, 97));
        jLabel6.setText("Check-In Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 54, -1, -1));
        jPanel1.add(guestName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 75, 175, -1));

        jLabel7.setForeground(new java.awt.Color(212, 171, 97));
        jLabel7.setText("Check-Out Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 54, -1, -1));
        jPanel1.add(guestName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 75, 175, -1));

        jLabel8.setForeground(new java.awt.Color(212, 171, 97));
        jLabel8.setText("Estimated Arrival:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 54, -1, -1));

        DoubleCheck.setText("Double");
        DoubleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleCheckActionPerformed(evt);
            }
        });
        jPanel1.add(DoubleCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        singleCheck.setText("Single");
        jPanel1.add(singleCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        TwinCheck.setText("Twin");
        jPanel1.add(TwinCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        ExecuteiveCheck.setText("Executive");
        jPanel1.add(ExecuteiveCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        DeluxeCheck.setText("Deluxe");
        jPanel1.add(DeluxeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        SuiteCheck.setText("Suite");
        jPanel1.add(SuiteCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        PresedentialCheck.setText("Presidential");
        jPanel1.add(PresedentialCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel20.setForeground(new java.awt.Color(212, 171, 97));
        jLabel20.setText("Add-Ons / Extra Services:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 110, -1, -1));

        jButton4.setText("Uncheck All");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        singleCheck1.setText("Laundry Service");
        jPanel1.add(singleCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 138, -1, -1));

        DoubleCheck1.setText("Mini Bar Access");
        DoubleCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleCheck1ActionPerformed(evt);
            }
        });
        jPanel1.add(DoubleCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 171, -1, -1));

        TwinCheck1.setText("Parking");
        jPanel1.add(TwinCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 205, -1, -1));

        singleCheck2.setText("Airport Pick-up");
        jPanel1.add(singleCheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 138, -1, -1));

        singleCheck3.setText("Extra Bed");
        jPanel1.add(singleCheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 171, -1, -1));

        singleCheck4.setText("Extra Linen");
        jPanel1.add(singleCheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 205, -1, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 204, -1, -1));
        jPanel1.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 170, -1, -1));

        jButton5.setText("Clear all");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 220, 120, -1));

        jButton6.setText("Reserve");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 260, 122, -1));

        jButton7.setText("Check Availablity");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoubleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleCheckActionPerformed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
       jCheckBox1.setSelected(true);
       DoubleCheck.setSelected(true);
       singleCheck.setSelected(true);
       TwinCheck.setSelected(true);
       ExecuteiveCheck.setSelected(true);
       DeluxeCheck.setSelected(true);
       SuiteCheck.setSelected(true);
    }//GEN-LAST:event_jButton4MousePressed

    private void DoubleCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleCheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleCheck1ActionPerformed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DeluxeCheck;
    private javax.swing.JCheckBox DoubleCheck;
    private javax.swing.JCheckBox DoubleCheck1;
    private javax.swing.JCheckBox ExecuteiveCheck;
    private javax.swing.JCheckBox PresedentialCheck;
    private javax.swing.JCheckBox SuiteCheck;
    private javax.swing.JCheckBox TwinCheck;
    private javax.swing.JCheckBox TwinCheck1;
    private javax.swing.JTextField guestName;
    private javax.swing.JTextField guestName1;
    private javax.swing.JTextField guestName2;
    private javax.swing.JTextField guestName3;
    private javax.swing.JTextField guestName4;
    private javax.swing.JTextField guestName5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox singleCheck;
    private javax.swing.JCheckBox singleCheck1;
    private javax.swing.JCheckBox singleCheck2;
    private javax.swing.JCheckBox singleCheck3;
    private javax.swing.JCheckBox singleCheck4;
    // End of variables declaration//GEN-END:variables
}
